Conflux-Chain/conflux-portal

- app/scripts/controllers/network/network.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/metamask-extension/7)
> Add: default usning testnet when dev, use localhost when test

- development/copy-alpha-release-to-server.sh
- docs/alpha-test-page.html
- docs/alpha-test-page.org
- package.json
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/metamask-extension/15)
> Add: alpha release files and commands

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- app/manifest.json
- app/scripts/platforms/extension.js
- docs/alpha-test-page.html
- docs/alpha-test-page.org
- ui/app/components/app/dropdowns/account-details-dropdown.js
- ui/app/components/app/gas-customization/advanced-gas-inputs/advanced-gas-inputs.component.js
- ui/app/components/app/transaction-list-item-details/transaction-list-item-details.component.js
- ui/app/ducks/gas/gas-duck.test.js
- ui/app/ducks/gas/gas.duck.js
----
- get default gas price through json rpc
- some "Etherscan" to "Confluxscan"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/metamask-extension/16)
> Release 0.0.2 version

- ui/app/ducks/gas/gas.duck.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/47)
> Fix: average estimate gas price unit

- CHANGELOG.md
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/50)
> Fix: changelog.md

- CHANGELOG.md
- app/manifest.json
- development/auto-changelog.sh
* Sync Version v0.0.9 RC (#58) from master (#60)
* Version v0.0.8 (#49)
Co-authored-by: yqrashawn <namy.19@gmail.com>
* Fix: changelog.md (#50)
* Fix e2e tests (#56)
* Add: arrow-parens eslint rule
* Attempt ENS resolution on any valid domain name (#8059)
ENS currently supports a variety of tlds in addition to `.eth`, and
more will be supported in the future. Rather than hard-code a list of
supported ENS tlds, all valid domain names will now be interpreted as
potential ENS addresses in our address input component.
Closes #7978
* Remove unused sinon sandboxes (#8063)
These sandboxes were created, then not utilized at all.
* Enable core ESLint no-mixed-operators rule
* Update redux-related dependencies (#8068)
* Add optional chaining (#8052)
* Add plugin-proposal-optional-chaining
* Use …
> Version v0.1.0 RC (#64)

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- test/unit/ui/etherscan-prefix-for-network.spec.js
- ui/lib/account-link.js
- ui/lib/etherscan-prefix-for-network.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/77)
> Fix: confluxscan url

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/scripts/controllers/detect-tokens.js
- app/scripts/controllers/fakeContractMapForTest.js
- test/e2e/send-edit.spec.js
- ui/app/components/app/confirm-page-container/confirm-page-container-content/confirm-page-container-content.component.js
- ui/app/components/app/gas-customization/advanced-gas-inputs/advanced-gas-inputs.container.js
- ui/app/components/app/modals/notification-modal/index.js
- ui/app/components/app/modals/notification-modal/notification-modal.component.js
- ui/app/components/app/modals/notification-modal/notification-modal.container.js
- ui/app/helpers/utils/conversions.util.js
- ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js
- ui/app/pages/send/send-content/send-hex-data-row/send-hex-data-row.component.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/126)
> Add: chinese trans in send and confirm page

- CHANGELOG.md
- app/manifest.json
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/130)
> master -> dev

- ui/app/components/app/transaction-view-balance/transaction-view-balance.component.js
- ui/app/components/ui/balance/balance.component.js
Closes #103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/129)
> modify decimal of balance

- ui/app/components/app/dropdowns/account-details-dropdown.js
Closes #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/131)
> bugfix: check whether keyring is null

- development/sentry-publish.js
----
resolve #142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/143)
> Fix: sentry project name

- Dockerfile
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/147)
> Fix: dockerfile, less build level

- Dockerfile
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/148)
> Add: format comments in dockerfile

- .buildkite/pipeline.yml
- Dockerfile
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/149)
> Fix: reorder task

- test/e2e/run-all-parallel.sh
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/150)
> Fix: buildkite can't get the right exit code from e2e bash script

- docs/QA_Guide.md
- docs/README.md
- docs/design-system.md
- docs/extension_description/en.txt
- docs/porting_to_new_environment.md
- docs/translating-guide.md
- test/e2e/contract-test/index.html
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/151)
> Docs: update documents

- ui/app/components/app/confirm-page-container/confirm-detail-row/confirm-detail-row.component.js
- ui/app/components/app/confirm-page-container/confirm-detail-row/tests/confirm-detail-row.component.test.js
- ui/app/pages/confirm-transaction-base/confirm-transaction-base.component.js
resolve #123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/157)
> Fix: hide conversion rate text

- .github/semantic.yml
check for details here
https://github.com/zeke/semantic-pull-requests#readme
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/161)
> chore: semantic.yml for semantic pr ci check

- Dockerfile
- app/scripts/controllers/detect-tokens.js
- app/scripts/controllers/permissions/enums.js
- development/local-node.js
- package.json
- test/e2e/helpers.js
- test/e2e/metamask-ui.spec.js
- test/e2e/simple-fixture-server.js
- yarn.lock
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/162)
> chore: use new js-conflux-sdk

- app/scripts/controllers/ens/ens.js
- package.json
- ui/app/helpers/utils/util.js
- ui/app/pages/send/send-content/add-recipient/ens-input.component.js
- ui/app/pages/send/tests/send-component.test.js
- yarn.lock
resolve #154
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/171)
> fix: remove ens error

- .circleci/config.yml
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/180)
> ci(changelog): automatically update changelog at pre release

- development/sentry-publish.js
- development/sentry-upload-artifacts.sh
resolve #106
(cherry picked from commit bad43c21a872f4be3b84345cb9f29398954e2964)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/181)
> fix: sentry sourcemap upload

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- ui/app/helpers/higher-order-components/i18n-provider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/190)
> docs(trans): Pontus -> Oceanus don't depends on time

- package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/191)
> chore: test with fullnode 0.6.0-rc3

- app/scripts/controllers/detect-tokens.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/192)
> fix(contract-manager-api): add pagination query params

- app/manifest.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/195)
> fix(permission): remove unused permissions

- CHANGELOG.md
- app/manifest.json
:package: :rocket:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/196)
> Version v0.3.2 RC

- ui/app/pages/send/send-content/add-recipient/ens-input.component.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/199)
> fix(add-recipient): remove ens error

- app/scripts/lib/get-first-preferred-lang-code.js
- test/e2e/metamask-ui.spec.js
- test/e2e/permissions.spec.js
- ui/app/pages/send/send-content/add-recipient/ens-input.component.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/200)
> fix(i18n): use only zh_CN zh_TW en

- CHANGELOG.md
- app/manifest.json
- app/scripts/lib/get-first-preferred-lang-code.js
- test/e2e/metamask-ui.spec.js
- test/e2e/permissions.spec.js
- ui/app/pages/send/send-content/add-recipient/ens-input.component.js
:package: :rocket:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/201)
> Version v0.3.3 RC

- app/scripts/controllers/network/enums.js
- app/scripts/lib/account-tracker.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-portal/204)
> fix: wrong chainId failing balance check

- ui/app/components/app/transaction-list-item-details/transaction-list-item-details.container.js
> fix(tx-list): toLowerCase error when display contract creation tx

- ui/app/pages/settings/security-tab/security-tab.component.js
- ui/app/pages/settings/security-tab/tests/security-tab.test.js
> fix: remove unused show incoming txs option

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- ui/app/pages/create-account/create-account.component.js
- ui/app/pages/create-account/import-account/index.js
- ui/app/pages/create-account/tests/create-account.test.js
- ui/app/pages/first-time-flow/create-password/import-with-seed-phrase/import-with-seed-phrase.component.js
- ui/app/pages/first-time-flow/create-password/new-account/new-account.component.js
- ui/app/pages/first-time-flow/metametrics-opt-in/metametrics-opt-in.component.js
- ui/app/pages/first-time-flow/metametrics-opt-in/metametrics-opt-in.container.js
> fix: more cn trans, remove hardware wallet tab, remove some doc

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
> fix: default network is not testnet anymore

- CHANGELOG.md
- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- app/manifest.json
> Version v0.3.8 RC

- app/scripts/controllers/transactions/index.js
- test/e2e/metamask-ui.spec.js
- test/unit/app/controllers/transactions/tx-controller-test.js
- ui/app/pages/send/send-content/send-gas-row/send-gas-row.container.js
- ui/app/pages/send/send.container.js
- ui/app/pages/send/send.utils.js
- ui/app/store/actions.js
> fix: check sponsor info for all tokens

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
- test/e2e/metamask-ui.spec.js
- test/unit/app/controllers/transactions/tx-controller-test.js
- ui/app/pages/send/send-content/send-gas-row/send-gas-row.container.js
- ui/app/pages/send/send.container.js
- ui/app/pages/send/send.utils.js
- ui/app/store/actions.js
> Version v0.3.9 RC

- app/scripts/controllers/transactions/pending-tx-tracker.js
> fix: add more knowntx error message

- app/scripts/controllers/permissions/enums.js
> feat: support cfx_clientVersion rpc method

- .circleci/scripts/release-create-gh-release
- CHANGELOG.md
- app/manifest.json
> Release: Version v0.4.2 RC

- app/scripts/controllers/network/enums.js
- app/scripts/controllers/network/util.js
- app/scripts/lib/buy-eth-url.js
- app/scripts/lib/enums.js
- app/scripts/lib/select-chain-id.js
- test/unit/app/buy-eth-url.spec.js
- test/unit/app/controllers/network/network-controller-test.js
- test/unit/ui/etherscan-prefix-for-network.spec.js
- ui/app/components/app/modals/deposit-ether-modal/deposit-ether-modal.component.js
- ui/lib/etherscan-prefix-for-network.js
> fix: testnet chainid

- .buildkite/scripts/pre
- CHANGELOG.md
- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/_locales/zh_TW/messages.json
- app/manifest.json
- app/scripts/controllers/network/enums.js
- app/scripts/controllers/network/network.js
- app/scripts/controllers/transactions/lib/recipient-blacklist-checker.js
- app/scripts/etherscan-link.js
- app/scripts/lib/buy-eth-url.js
- app/scripts/lib/ens-ipfs/setup.js
- app/scripts/lib/enums.js
- app/scripts/lib/select-chain-id.js
- app/scripts/metamask-controller.js
- package.json
- test/unit/app/controllers/transactions/recipient-blacklist-checker-test.js
- ui/app/components/app/dropdowns/network-dropdown.js
- ui/app/components/app/loading-network-screen/loading-network-screen.component.js
- ui/app/components/app/modals/deposit-ether-modal/deposit-ether-modal.component.js
- ui/app/components/app/network.js
- ui/app/components/app/transaction-activity-log/transaction-activity-log.component.js
- ui/app/components/app/transaction-view-balance/transaction-view-balance.component.js
- ui/app/components/ui/balance/balance.component.js
- ui/app/helpers/utils/transactions.util.js
- ui/app/pages/routes/index.js
- ui/app/pages/settings/networks-tab/networks-tab.component.js
- ui/lib/account-link.js
- yarn.lock
> refactor: Merge branch 'master' into develop

- CHANGELOG.md
- app/manifest.json
- package.json
- yarn.lock
> Release: Version v0.5.6 RC

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
- app/scripts/controllers/transactions/tx-state-manager.js
- test/unit/app/controllers/transactions/tx-controller-test.js
> Release: Version v0.5.7 RC

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
- ui/app/components/app/gas-customization/gas-modal-page-container/advanced-tab-content/advanced-tab-content.component.js
- ui/app/components/app/gas-customization/gas-modal-page-container/tests/gas-modal-page-container-container.test.js
- ui/app/components/app/modals/cancel-transaction/cancel-transaction.container.js
- ui/app/components/app/transaction-list-item/transaction-list-item.component.js
- ui/app/components/app/transaction-list-item/transaction-list-item.container.js
- ui/app/ducks/gas/gas-duck.test.js
- ui/app/ducks/gas/gas.duck.js
- ui/app/helpers/constants/common.js
- ui/app/helpers/utils/confirm-tx.util.js
- ui/app/helpers/utils/conversion-util.js
- ui/app/selectors/selectors.js
> Release: Version v0.5.8 RC

- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/scripts/background.js
- app/scripts/controllers/network/createMetamaskMiddleware.js
- app/scripts/controllers/network/middleware/pending.js
- app/scripts/controllers/transactions/index.js
- app/scripts/controllers/transactions/pending-tx-tracker.js
- app/scripts/controllers/transactions/tx-state-manager.js
- app/scripts/lib/reportFailedTxToSentry.js
- test/unit/app/controllers/transactions/pending-tx-test.js
- ui/app/components/app/transaction-status/index.scss
- ui/app/components/app/transaction-status/transaction-status.component.js
- ui/app/helpers/constants/transactions.js
- ui/index.js
> fix: add status for tx missing `rawTx`

- app/_locales/en/messages.json
- app/_locales/index.json
- app/_locales/zh_CN/messages.json
- app/scripts/lib/get-first-preferred-lang-code.js
- app/scripts/portal-inpage.js
- package.json
- test/e2e/from-import-ui.spec.js
- test/e2e/metamask-ui.spec.js
- ui/app/css/itcss/components/new-account.scss
- ui/app/pages/create-account/create-account.component.js
- ui/app/pages/create-account/new-account.component.js
- ui/app/pages/create-account/new-account.container.js
- yarn.lock
> feat: add/restore account

- app/scripts/controllers/detect-tokens.js
> fix: token balance not showing automatically

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/detect-tokens.js
> Release: Version v0.5.11 RC

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/detect-tokens.js
Merge latest release back into develop
> refactor: Master => develop

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/network/network.js
> Release: Version v0.6.1 RC

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
> Release: Version v0.6.5 RC

- CHANGELOG.md
- app/_locales/en/messages.json
- app/_locales/zh_CN/messages.json
- app/manifest.json
- ui/app/helpers/utils/token-util.js
- ui/app/pages/add-token/add-token.component.js
> Release: Version v0.6.6 RC

- CHANGELOG.md
- app/manifest.json
- ui/app/ducks/gas/gas-duck.test.js
- ui/app/ducks/gas/gas.duck.js
> Release: Version v0.6.10 RC

- .buildkite/pipeline.yml
- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
- ui/app/ducks/gas/gas-duck.test.js
- ui/app/ducks/gas/gas.duck.js
> Release: Version v0.6.11 RC

- CHANGELOG.md
- app/manifest.json
- app/scripts/controllers/transactions/index.js
- ui/app/ducks/gas/gas.duck.js
> Release: Version v0.6.12 RC
